narrowing_conversions: narrowing_conversions.cpp
	mkdir -p build/
	# c++ -O3 -Wall -Wextra -Wno-unused-variable -Wconversion -std=c++17 -o build/narrowing_conversions narrowing_conversions.cpp
	c++ -O3 -Wall -Wextra -Wno-unused-variable -std=c++17 -o build/narrowing_conversions narrowing_conversions.cpp
clean:
	rm -f build/narrowing_conversions