composite_design_pattern: composite_design_pattern.cpp
	mkdir -p build/
	c++ -O3 -Wall -Wextra -std=c++20 -o build/composite_design_pattern composite_design_pattern.cpp
clean:
	rm -f build/composite_design_pattern