template_type_deduction: template_type_deduction.cpp
	mkdir -p build/
	c++ -O3 -Wall -Wextra -std=c++17 -o build/template_type_deduction template_type_deduction.cpp

clean:
	rm -f build/template_type_deduction